
server:
  #?????
  port: 9639 #?????8080
spring:
  datasource:
    #??????
    username: root
    #???????
    password: root
    #serverTimezone=UTC ??????? ??mysql?8.0??????????
    #userUnicode=true&characterEncoding=utf-8 ???????????
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    #?????
    driver-class-name: org.postgresql.Driver
    #?????
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot ???????????????????
    #druid ???????
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #?????????filters?stat:?????log4j??????wall???sql??
    #???????  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #??? log4j ?????Maven ???https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# ??mybatis
mybatis:
  #??pojo??????mybatis?????????pojo??
  type-aliases-package: com.zeal
  #??????Mapper?????XML?? classpath:xml????
  mapper-locations: classpath:mapper/*.xml
